In [1]:
import numpy as np # import = 불러오는 것 , as = 줄여서 부르는 것

my_list = list(range(1000000))
my_array = np.arange(1000000)

In [3]:
%timeit my_list2 = [i * 2 for i in my_list]
%timeit my_array2 = my_array * 2

49.2 ms ± 190 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.96 ms ± 25.9 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [136]:
a = [
    [1, 1.2, 3], # 소수를 포함하므로 뒤에 .으로 구분
    [-123, 123, 0],
]
data = np.array(a)
print(data)

[[   1.     1.2    3. ]
 [-123.   123.     0. ]]


In [137]:
# 0차원 : 스칼라(scala) => 단일데이터로 생각, 1차원 : 벡터(vector), 
# 2차원 : 행렬(matrix), 3차원 : 텐서(tenser)
print(data * 10)
print(data + data)

[[   10.    12.    30.]
 [-1230.  1230.     0.]]
[[   2.     2.4    6. ]
 [-246.   246.     0. ]]


In [138]:
print(data.shape) 
print(data.dtype)

(2, 3)
float64


## ndarray 생성하기

In [147]:
data1 = [1, 2, 3, 4, 5]
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [151]:
arr2 = np.array([[1.1, 2.2], [3.3, 4.4]])
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [152]:
print(arr1.ndim)
print(arr2.ndim) # ndim: 차원

1
2


In [153]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 2)


In [54]:
# print([0] * 10)
print(np.zeros(10))
print(np.zeros((5, 5)))
print(np.empty((2, 2, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [39]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


## ndarray 자료형

In [41]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [43]:
arr1 = np.array([1, 2, 3])
print(arr1.dtype)
float_arr1 = arr1.astype(np.float64) # 형변환 함수
print(float_arr1)
print(float_arr1.dtype)

int64
[1. 2. 3.]
float64


In [47]:
arr2 = np.array([1.1, 2.2, 3.3]) # 소수점 뒤는 버림
print(arr2.dtype)
int_arr2 = arr2.astype(np.int64)
print(int_arr2)
print(int_arr2.dtype)

float64
[1 2 3]
int64


## 산술 연산

In [51]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr * arr) 
print(arr + arr)
print(1 / arr)
print(arr ** 3)
# 같은 위치의 값을 계산

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [53]:
arr2 = np.array([[3, 2, 1], [1, 2, 3]])
print(arr)
print(arr2)
print(arr > arr2)
print(arr == 3)
# 각각 위치에 있는 데이터를 비교

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[False False  True]
 [False False False]]


## 색인(인덱싱)과 슬라이싱

In [55]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [58]:
print(arr[5])
print(arr[2:5])

5
[2 3 4]


In [61]:
arr[2:5] = 10
print(arr)

[ 0  1 10 10 10  5  6  7  8  9]


In [63]:
py_list = [1, 2, 3, 4, 5]
py_list[2:3].pop()
print(py_list)
# python은 슬라이싱을 해도 원본은 유지되지만 numpy는 일부 수정하더라도 원본에 반영

[1, 2, 3, 4, 5]


In [139]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr) 

[[1 2 3]
 [4 5 6]]


In [140]:
print(arr[1][1]) # 0: [1 ,2, 3] , 1: [4, 5, 6]
print(arr[1, 1])

5
5


In [141]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
                  [[11, 12, 13], [14, 15, 16], [17, 18, 19]], 
                  [[11, 22, 33], [44, 55, 66], [77, 88, 99]]])
# 0: [[1, 2, 3], [4, 5, 6], [7, 8, 9]] , 
# 1: [[11, 12, 13], [14, 15, 16], [17, 18, 19]] ,
# 2: [[11, 22, 33], [44, 55, 66], [77, 88, 99]]

In [75]:
print(arr3d[2][0][1])
print(arr3d[2, 0, 1])

22
22


In [143]:
arr3d[0, 1:, 2:]

array([[6],
       [9]])

In [81]:
arr3d[0, 1:, 2:] = 9999
print(arr3d)

[[[   1    2    3]
  [   4    5 9999]
  [   7    8 9999]]

 [[  11   12   13]
  [  14   15   16]
  [  17   18   19]]

 [[  11   22   33]
  [  44   55   66]
  [  77   88   99]]]


## 불리언 값으로 선택

In [84]:
names = np.array(['hong', 'kim', 'hong', 'kim'])
data = np.array([['math', 60], ['math', 90], ['eng', 70], ['eng', 50]])

In [86]:
names == 'hong'

array([ True, False,  True, False])

In [89]:
# data[[True, False, True, False]]
data[names == 'hong']

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [91]:
print(data[names == 'hong', 1])
print(data[names == 'hong', :1])

['60' '70']
[['math']
 ['eng']]


In [94]:
print(names != 'hong') # 'hong'이 아닌 사람을 구하는 것
print(~(names == 'hong'))

[False  True False  True]
[False  True False  True]


In [95]:
cond = names == 'kim'
data[cond]

array([['math', '90'],
       ['eng', '50']], dtype='<U21')

## 팬시 색인 (fancy indexing)

In [155]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i]=i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [156]:
arr[[4, 3, 0, 5]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [157]:
arr[[-3, -5, -1]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [158]:
arr = np.arange(32).reshape(8, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [159]:
arr[[1,5], [2, 3]] # [1][2] , [5][3] 으로 나누어서 생각

array([ 6, 23])

In [160]:
arr[[1, 5]][:, [2, 3]]

array([[ 6,  7],
       [22, 23]])

## 배열 전치

In [115]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [116]:
print(arr.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [118]:
# 행렬의 내적, 곱
print(arr @ arr.T)
print(np.dot(arr, arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


## numpy 함수

In [120]:
samples = np.random.standard_normal(size=(3,3))
print(samples)

[[ 1.23714331  0.00666165 -0.55029608]
 [-1.15713981  0.73853391  0.15067953]
 [ 0.03528397  0.33423404  1.82684126]]


In [124]:
arr1 = np.sqrt(samples) # nan => 숫자가 아닙니다. 루트를 씌웠는데 숫자가 음수일 경우 발생, 결측치라고 많이 부름
print(arr1)

[[1.11226944 0.08161895        nan]
 [       nan 0.85937995 0.38817461]
 [0.18784028 0.57812977 1.35160692]]


C:\Users\1-03\AppData\Local\Temp\ipykernel_12644\2581806402.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples) # nan => 숫자가 아닙니다. 루트를 씌웠는데 숫자가 음수일 경우 발생, 결측치라고 많이 부름


In [126]:
arr2 = np.abs(samples) # abs => 절대값으로 바꿔줌
print(arr2)

[[1.23714331 0.00666165 0.55029608]
 [1.15713981 0.73853391 0.15067953]
 [0.03528397 0.33423404 1.82684126]]


In [127]:
np.isnan(arr1)

array([[False, False,  True],
       [ True, False, False],
       [False, False, False]])